version: "3.9"
services:

  db:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: cityapi
      POSTGRES_DATABASE: cityapi
      POSTGRES_USER: cityapi

  quarkus-app:
    image: custom-quarkus-app
    build:
      context: ./
      dockerfile: Dockerfile-quarkus
    env_file:
      - .env
    command: ./cityapi-1.0.0-SNAPSHOT-runner
    ports:
      - "8080:8080"



