FROM ghcr.io/graalvm/graalvm-ce:ol9-java17 as builder

# Add native image support
RUN gu install native-image

# Copy the source files
COPY ./ /opt/build
WORKDIR /opt/build

RUN ./gradlew init

# Build the app, without tests
RUN ./gradlew build -Dquarkus.package.type=native -x test

FROM debian:bookworm-slim as runner

RUN mkdir -p "/opt/app"
COPY --from=builder /opt/build/build/*-runner /opt/app

WORKDIR /opt/app

CMD ["./cityapi-1.0.0-SNAPSHOT-runner", "-Dquarkus.http.host=0.0.0.0"]